apiVersion: apps/v1
kind: Deployment
metadata:
  name: aviation-compliance-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aviation-compliance-backend
  template:
    metadata:
      labels:
        app: aviation-compliance-backend
    spec:
      containers:
      - name: aviation-compliance-backend
        image: aviationbackend.azurecr.io/aviation-compliance:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: PYTHONPATH
          value: "/app"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: aviation-compliance-backend-service
spec:
  selector:
    app: aviation-compliance-backend
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer