# render.yaml para deploy automático no Render
services:
  - type: web
    name: aviation-compliance-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: ENVIRONMENT 
        value: production
      - key: API_HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: aviation-compliance-api
          property: port